name: doctors_prescription
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.4
  firebase_storage: ^3.1.5 # NO WEB SUPPORT
  provider: ^4.3.2+2
  email_validator: ^1.0.4
  toggle_bar_button: ^1.0.0 # NO WEB SUPPORT
  camera: ^0.5.7+4 # NO WEB SUPPORT
  path_provider: ^1.6.5 # NO WEB SUPPORT
  path: ^1.6.4
  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.0.12 # NO WEB SUPPORT
  flare_flutter: ^2.0.1
  http: ^0.12.0+4 # REMOVE LATER
  dio: ^3.0.10
  image: ^2.1.4
  shared_preferences: ^0.5.10
  google_fonts: ^1.1.0 # NO WEB SUPPORT
  intl: ^0.16.1
  age: ^0.0.1
  image_cropper: ^1.3.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  string_similarity: ^1.1.0
  cached_network_image: ^2.3.3






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
